services:
  accounts:
    image: "babureddy9119/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - babureddy
  loans:
    image: "bubureddy9119/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - babureddy
  cards:
    image: "babureddy9119/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - babureddy
networks:
  babureddy:
    driver: "bridge"